### ISSUE TITLE
pdl/pdlopen component fail when compiled statically

### ISSUE THREAD

**Issue by jsquyres** [pmix/pmix#1121]
Cisco's Open MPI MTT is seeing linker failures when trying to link MPI test applications when Open MPI (master) has been built statically with the embedded PMIx (4.x) with the pdl/pdlopen component:

```
/home/mpiteam/scratches/community/2019-02-11cron/VebM/installs/JgCi/install/lib/libopen-pal.a(pdl_pdlopen_module.o):
In function `do_pdlopen':
pdl_pdlopen_module.c:(.text+0x44): undefined reference to `dlopen'
pdl_pdlopen_module.c:(.text+0x73): undefined reference to `dlerror'
/home/mpiteam/scratches/community/2019-02-11cron/VebM/installs/JgCi/install/lib/libopen-pal.a(pdl_pdlopen_module.o):
In function `pdlopen_lookup':
pdl_pdlopen_module.c:(.text+0x384): undefined reference to `dlsym'
pdl_pdlopen_module.c:(.text+0x3ad): undefined reference to `dlerror'
/home/mpiteam/scratches/community/2019-02-11cron/VebM/installs/JgCi/install/lib/libopen-pal.a(pdl_pdlopen_module.o):
In function `pdlopen_close': 
pdl_pdlopen_module.c:(.text+0x3f9): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
```

For example: https://mtt.open-mpi.org/index.php?do_redir=3164

I'm guessing the `pdl` framework was copied from Open MPI's `dl` framework, and after a quick troll through Open MPI's `dl`, I'm afraid I don't remember what we did to avoid this issue on the Open MPI side...?

**Comment by rhc54** [comment]
Odd - just comparing OMPI to PMIx frameworks, it appears a major change was done to the OMPI one at some point after we copied it. I don't see a post_config section in the dlopen component for OMPI, but we have one for PMIx. I wonder if that's the difference?

**Comment by rhc54** [comment]
I found one difference (other than that post_config), but I'm not sure how to resolve it. OMPI has the following in the dlopen component's configure.m4:
```shell
           dl_dlopen_WRAPPER_EXTRA_LIBS=$opal_dl_dlopen_LIBS
```
PMIx doesn't have the equivalent because we don't have wrapper compilers. Is it possible that this is what breaks the app compile under static builds?

**Comment by rhc54** [comment]
I just built PMIx master ```--enable-static --disable-shared``` and then used it with PRRTE to compile test apps using the ```pcc``` wrapper compiler. Everything built and ran fine, so I suspect this is an OMPI configure issue.

**Comment by ggouaillardet** [comment]
@rhc54 I think the issue here is `pmix` should not build the `pdl/pdlopen` component
(fwiw, Open MPI does not build the `dl/dlopen` component.

Long story short, when we `configure --disable-dlopen`, Open MPI calls `opal/mca/dl/configure.m4` with `enable_dlopen=no`, but PMIx calls `src/mca/pdl/configure.m4` with `enable_dlopen=unknown`, and this is set by `config/libtool.m4` (Open MPI will eventually set `enable_dlopen=unkwnon` but later).
I am tempted to conclude it is not safe to use the `$enable_dlopen` variable, and though Open MPI is lucky, PMIx is not ...

@jsquyres any thoughts ?

the inline patch below is a band aid that does the trick for Open MPI

```patch
diff --git a/opal/mca/pmix/pmix4x/pmix/src/mca/pdl/configure.m4 b/opal/mca/pmix/pmix4x/pmix/src/mca/pdl/configure.m4
index c508206..82f8c23a 100644
--- a/opal/mca/pmix/pmix4x/pmix/src/mca/pdl/configure.m4
+++ b/opal/mca/pmix/pmix4x/pmix/src/mca/pdl/configure.m4
@@ -27,7 +27,7 @@ AC_DEFUN([MCA_pmix_pdl_CONFIG],[
     # (we still need to configure them all so that things like "make
     # dist" work", but we just want the MCA system to (artificially)
     # conclude that it can't build any of the components.
-    AS_IF([test "$enable_dlopen" = "no"],
+    AS_IF([test "$enable_dlopen" = "no" || test "$enable_dlopen" = "unknown"],
           [want_pdl=0], [want_pdl=1])
 
     MCA_CONFIGURE_FRAMEWORK([pdl], [$want_pdl])
@@ -35,7 +35,7 @@ AC_DEFUN([MCA_pmix_pdl_CONFIG],[
     # If we found no suitable static pdl component and dlopen support
     # was not specifically disabled, this is an error.
     AS_IF([test "$MCA_pmix_pdl_STATIC_COMPONENTS" = "" && \
-           test "$enable_dlopen" != "no"],
+           test "$want_pdl" = "1"],
           [AC_MSG_WARN([Did not find a suitable static pmix pdl component])
            AC_MSG_WARN([You might need to install libltld (and its headers) or])
            AC_MSG_WARN([specify --disable-dlopen to configure.])
```

FWIW, from `config/libtool.m4`

```
# LT_SYS_DLOPEN_SELF
# ------------------
AC_DEFUN([LT_SYS_DLOPEN_SELF],
[m4_require([_LT_HEADER_DLFCN])dnl
if test "x$enable_dlopen" != xyes; then
  enable_dlopen=unknown
  enable_dlopen_self=unknown
  enable_dlopen_self_static=unknown
```

**Comment by rhc54** [comment]
@ggouaillardet If the user doesn't specify dlopen (either enable or disable) on the configure cmd line, does libtool default it to "unknown"? Just wondering if we might wind up defaulting it in the wrong direction.

**Comment by ggouaillardet** [comment]
@rhc54 yes, this is what I read.
Open MPI seems to work fine because `enable_dlopen=unknown` is done __after__ our test (PMIx does that __before__ our test and I did not try to understand how we could swap these)

From `config/opal_configure_options.m4`

```if test "$enable_dlopen" = "no" ; then
    enable_mca_dso=no
    enable_mca_static=yes
    OPAL_ENABLE_DLOPEN_SUPPORT=0
    AC_MSG_RESULT([no])
else
    OPAL_ENABLE_DLOPEN_SUPPORT=1
    AC_MSG_RESULT([yes])
fi
```

I think the easiest fix would be to use `$OPAL_ENABLE_DLOPEN_SUPPORT` instead of `$enable_dlopen`.
We could also add a test here `if "$enable_dlopen" = "unknown"` to abort `configure` and tell the end users to file a bug.

By the way, do you remember the difference between `--disable-dlopen` and `--disable-mca-dso` ?
it seems these two options could be synonymous (and that would simplify things a bit)

**Comment by rhc54** [comment]
> I think the easiest fix would be to use `$OPAL_ENABLE_DLOPEN_SUPPORT` instead of `$enable_dlopen`

I'm not sure how that would work down in PMIx - are you thinking we would "reset" the configure cmd line for the pmix component based on that value? Will that cause any problems for follow-on code (i.e., since we would now "reset" ```enable_dlopen=unknown``` to a value?

> By the way, do you remember the difference between --disable-dlopen and --disable-mca-dso ?

I honestly don't - perhaps @bwbarrett would recall?

**Comment by ggouaillardet** [comment]
@rhc54 a PR being worth a thousand words, I issued #1191 in order to clarify what I meant.

Unlike `config/opal_mca.m4`, `config/pmix_mca.m4` does not set `enable_dlopen`, so that makes PMIx trivial to update.
