### ISSUE TITLE
Naked memory function (malloc, calloc, free) in pmix_common.h

### ISSUE THREAD

**Issue by hzhou** [pmix/pmix#1312]
## Background information

MPICH has a memory tracing facility by tracking memory functions such as `malloc`, `free`. This is currently done through macros, and requires all memory functions inside MPICH be wrapped. Currently, this option is incompatible with PMIX as its API header files contains naked `malloc` and `free`.

xref: https://github.com/pmodels/mpich/issues/3832

### What version of the PMIx Reference Library are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

At the moment, I was building from git master @35de87e1aad7b245f35fa57a6c10a8e92e2763e4

### Describe how PMIx was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

`git clone` into custom folder.

### Please describe the system on which you are running

* Operating system/version: linux/ubuntu 18.04

-----------------------------

## Details of the problem

While pondering on work around solutions -- all nasty -- I can't help thinking that this is PMIx api issue and it is easy to fix here. For example, how about turn these macros -- `_CREATE`, `_FREE`, `_DESTRUCT` into inline functions? Of course, personally, I would like to see them as real functions but we may have different view on what is performance critical. Is it possible to make it a build option (inline vs. normal functions)? To the least, if they need be in macros, are they complete? That is, for all memory that call `free` in the macros, are they all allocated by the macros? As long as they are balanced, then it won't necessarily break memory tracing facilities. If that is the case, one solution maybe use `pmix_malloc`, `pmix_free` etc. in stead of naked calls, and they can be redefined to whatever.

**Comment by rhc54** [comment]
Just to be certain we are on the same page here, those macros are purely for users' convenience - there is no requirement that someone use them. The easiest solution (at least, for now) would be to just not use them inside MPICH, or to create your own copies of them that use your macro wrappers around the memory operations.

Note that although these macros are used inside PMIx as well, I don't believe you'll be able to intercept our internal memory operations as there are lots of malloc/free operations that don't use the user-facing macros. They _should_ balance out between PMIx_Init and PMIx_Finalize, but...

All that aside, I have no issue with using inline functions here. We'll need to retain the macros for backward compatibility (can't break existing code bases), but we can have the macro simply call an inline function. PMIx is not a performant library and should never be used in a critical path as it interacts with system management elements (which are definitely _not_ performant in an MPI sense), but that doesn't mean we don't care about performance at all. We just don't believe it to be performance critical (at least, in an MPI sense - i.e., PMIx should never impact the performance of the library using it).

If you would like to contribute that change, we would welcome it. Otherwise, I'll try to get to it in a couple of weeks as I'm rather tied up right now.

**Comment by rhc54** [comment]
@hzhou Does #1321 look like an acceptable solution to you? If so, I can extend to the other macros - just want to ensure we are going down a path that solves the problem.

**Comment by hzhou** [comment]
@rhc54 Yes, I think it will solve our memory tracing issue. Thanks for doing this.
