### ISSUE TITLE
buffer ops segfault in release version

### ISSUE THREAD

**Issue by artpol84** [pmix/pmix#787]
We found this while tracking a bug in Slurm plugin.
If a wrong buffer was returned in the PMIx modex callback release version of PMIx will segfault, while debug one will detect the problem and return with an error.
I assume that this is expected as in release mode buffers do not have enough information to identify the problem, however, I thought it is worth to double-check.

**Comment by artpol84** [comment]
Actually, after thinking about that I think it is more a bug than a feature. 
As buffer boundaries are known, there shouldn't be a SIGSEGV in this case in release version.

**Comment by rhc54** [comment]
I'm not sure there is enough info here to know if a segv could be avoided or not. When built in optimized mode, the buffer doesn't contain any object identification info and so the code relies on the return being correct. What should have happened is that the debug version reveals the problem and it gets fixed before using an optimized version.

Consider the case where there are enough bytes remaining in the buffer for the code to unpack the requested object, but the bytes actually are from some other kind of object because the ordering is wrong (or in this case, the buffer is incorrect). You'll get an object returned that has garbage in its fields but there is no way to detect it...and you will likely segfault. I don't see any way to avoid it unless you get lucky and don't have enough bytes to do the unpack.

**Comment by rhc54** [comment]
reopen if there is a further question

**Comment by artpol84** [comment]
@rhc54 sorry for the late respond - thank you for the explanation.
