### ISSUE TITLE
Question: using PMIx in task-based environments

### ISSUE THREAD

**Issue by angainor** [pmix/pmix#807]
Please forgive me if this is not the correct place to ask questions - I looked at the google lists, but they seem quiet..

From what I know, PMIx is mostly used to exchange wire-up information between MPI ranks. However, I am wondering if it is possible / makes sense to use PMIx in a different way - to obtain information about local 'neighbors' (communication peers) in a task-based execution model.

Let me explain what I mean. Assume we implement a parallel PDE solver on a grid, or and adaptive mesh. Using some domain decomposition scheme of choice we split the domain into small sub-domains, and assign computations within those domains to 'tasks'. As you know, on the sub-domain borders we need to exchange the 'halo' (ghost zone) information. In a static execution model information about the neighbors can be provided by the user at startup time. But in a task-based model it's not the case: the tasks are scheduled by the task execution framework, and in general know nothing about any domain decomposition stuff. Still, they (or the framework) need to know how to contact their neighbors, and in fact - who their neighbors are at all. You could tweak this to set up the neighborhood information at startup, but in general the tasks can be divided, merged, and migrated at any time to a different Processing Element, and so their 'address' can change.

So what we need is a mechanism to update the task-local information about it's peers in a dynamic environment. Although I am not into the PMIx architecture (yet..), I have a hunch that there are possibilities here. I would really appreciate your comments.

Thanks a lot!

Marcin

**Comment by rhc54** [comment]
Most discussion has been taking place on issues, but the list is fine too.

The execution orchestrator would need to launch the processes via a PMIx-enabled RM to make it work, or establish a network of its own PMIx-enabled daemons. Assuming that is the case, then you could take advantage of the proposed PMIx Group capabilities (see https://pmix.org/pmix-standard/pmix-groups/) to construct/destruct the domains you describe.

Would that work for you?

**Comment by angainor** [comment]
@rhc54 Thanks, Ralph! We are in a rather early design stage, so I don't really know what I need, but what I think would be necessary is some means to locate a task on the used compute nodes. The information I have is the compute node that at some point was executing a given task. It could still be there, or it could have been migrated / split etc. So I imagine the API I would need is sort of

```
task_addr_t locate_task(task_id, old_task_addr);
```

The orchestrator would of course be able to notify the API about task migration and division. The goal of the API would be to provide the target task address 'fast'. I imagine we could implement this using some task chasing algorithm, but I was hoping there is something we can re-use.

Also, a task is actually just description of work (data), and not the same as a process (or thread), which complicates things further. And the tasks are not really working in groups. They each have a set of neighbors, but that's unique to each task. So the number of groups would be the same as the number of tasks.

I guess I need to first read about the general PMIx design to know, if we could use it.

**Comment by rhc54** [comment]
I think there are a couple of issues here. First, the notion of what is a task vs a group vs work/data lies outside of PMIx - it would be up to the host environment to define what it is tracking. All PMIx cares about is that there be an identifier assigned to each unit.

Second, your suggested API has an inherent race condition in it as you cannot know if the task migrated multiple times since the last time you requested its location. Thus, the "old" task address may be out of date. It isn't clear to me why you even need it as the task_id is required to be unique - so don't you just need to know where it now is?

Regardless, the information will always represent a race condition as you cannot know where a task actually "is" right at this moment - best you can do is to learn where it was when last reported, which isn't the same thing. Hence, a programming model that relies on knowing the location of a process is inherently fragile.

In PMIx-land, what we would do is have a process register for migration events. Thus, any time a proc migrates to another node, you'll get notified about it. You still won't know with certainty where a proc is at any instant in time, but at least you'll know where it was last reported to have been.

HTH

**Comment by angainor** [comment]
> In PMIx-land, what we would do is have a process register for migration events. Thus, any time a proc migrates to another node, you'll get notified about it. You still won't know with certainty where a proc is at any instant in time, but at least you'll know where it was last reported to have been.

Can one compute node register to receive migration events from another compute node? Say, a task A on node 1 knows that some task B that it will communicate to runs on node 2. The orchestrator on node 1 registers on node 2 to receive migration event of task B. Then, whenever task B is moved, the orchestrator on node 1 is informed about where it moved. It can then contact that destination for further assistance.

Ideally, the migration procedure would also re-register the task migration events on the target, so disregarding the race condition node 1 would have an up-to-date migration path, and a possible final destination.

**Comment by rhc54** [comment]
Any process that registers for migration events (using the PMIX_ERR_PROC_MIGRATE code) will receive them. If you want to only receive notification of the migration of a specific proc, then you include the PMIX_EVENT_AFFECTED_PROC attribute with that proc's identifier.  Registrations are persistent, so there is no need to "re-register" every time.

I'm not quite sure who in your system is managing these migrations. From your comments, I'm assuming that there is some resource manager (and not your orchestrator) moving the procs around, which is why your orchestrator doesn't know about it. In that case, here is what I would suggest:

- The orchestrator registers to receive migration events about anyone in the job. We give you an attribute to indicate that you would like the RM to provide the initial node and the destination node for that process in the notification so the orchestrator can track movement
- The orchestrator can generate its own event code to inform tasks about movements. PMIx will provide alerts to any code, not just those defined by PMIx itself. This allows the orchestrator to "target" who receives this particular event so you don't unnecessarily disturb other procs.
- Your procs register to receive your internal code. They will only receive it if they fall within the target range (or list of targets) specified by the orchestrator

HTH

**Comment by angainor** [comment]
Thanks a lot, Ralph! It certainly sounds like what we need could be doable with PMIx. I'll chew through the specs. Since we are on the design stage, it will take time before we have anything working. But if we end up using PMIx, I'll certainly let you know how.

Thanks again!

Marcin

**Comment by angainor** [comment]
@rhc54 Hello, Ralph,

I've been reading through the PMIx specs and code, and this lengthy post is mostly for me to understand better the design and idea. Probably I still don't have a good enough understanding of what PMIx does, and hence more questions ;) I really hope you can shed some light.

As I now understand, the PMIx library only manages local communication between clients and the local server / KV store. The information published / commited by the clients is then passed to the host SMS. If a remote client requests some information, exchange of data between the remote PMIx servers is performed by the SMS. So are the collectives.

First a somewhat philosophical question - what were the reasons for this choice? In principle, the PMIx server-side library could be made responsible for data exchange between servers that have clients belonging to, e.g., the same namespace. The advantage I see with this solution is that these transfers could be well optimized inside the PMIx library - a task, which the RM implementers will probably not do. For example, in my particular use case I need to track migrating and changing tasks. Although technically task location is global information, in practice only task's neighbors will need it. So there is no need to perform a one-to-all communication step after every migration, but instead the information could be gathered on a need-to-know basis. Maybe using some single-sided RMA comm. I am not sure how this data exchange is implemented now in orted, nor in SLURM, but I guess the simplest solution for an RM to implement is namely through a one-to-all (or all-to-all) collective. 

Clearly, on an exa-scale system it would be best to avoid the collective, which is also mentioned in the PMIx specs: "[...] While the stated objective of the PMIx community is to eliminate collective operations, it is recognized that the traditional method of publishing/exchanging data must be supported until that objective can be met. [...]". So assuming that the data exchange will remain a responsibility of the SMS, how will the collectives be eliminated?

Some other benefits of implementing server comm inside PMIx would be a wide support for events. For example, I see that SLURM in it's current form does not support events and notifications. So in order for me to implement what you suggested, i.e., use events to spread information about task migration I would have to implement a new (and sophisticated) SLURM mpi plugin, or force the users to stay with OpenMPI + orted.

Regarding that, could you briefly tell me what kind of algorithm is currently implemented in orted? Are all servers notified about the events (collective), or only those, which have clients, who registered for those events?

I also have a technical question regarding triggering of the data exchange. I see that committed data is collected in a call to PMIx_Fence(), which takes a list of processes that should participate, and can optionally exchange the data between them. But since a fence is a collective operation, it needs to be executed by all procs in the list at the same time. How do I notify all involved servers about the need to call the collective? It seems that it takes another collective, so I must have missed something?

**Comment by rhc54** [comment]
> As I now understand, the PMIx library only manages local communication between clients and the local server / KV store. The information published / commited by the clients is then passed to the host SMS. If a remote client requests some information, exchange of data between the remote PMIx servers is performed by the SMS. So are the collectives.

This is correct

> First a somewhat philosophical question - what were the reasons for this choice?

We spent quite a bit of time debating this point. It finally came down to a request from the RMs that we _not_ create our own separate communication system as it results in another messaging layer in the system (the RMs plus whatever is embedded in the library plus whatever PMIx used). We are dependent on the willingness of the RMs to support PMIx, so this was a request we honored.

> Clearly, on an exa-scale system it would be best to avoid the collective, which is also mentioned in the PMIx specs: "[...]  [...]". So assuming that the data exchange will remain a responsibility of the SMS, how will the collectives be eliminated?

We already have the mechanisms for doing this in the Standard and in prototype form. In brief, the RM calls a PMIx API with the allocation and job mapping prior to sending the launch msg to the compute nodes. PMIx contains a fabric plugin that pre-assigns endpoints to each process, and then returns the resulting "blob" to the RM for distribution in the launch msg. Once the msg reaches a compute node, the local RM daemon passes the "blob" to PMIx (via a separate API) for processing - this can involve pre-conditioning the local fabric drivers as well as adding envars to the individual procs. End result is that every PMIx server can provide the endpoint for any process in the job without having to obtain the information via data exchange.
 
> Some other benefits of implementing server comm inside PMIx would be a wide support for events. For example, I see that SLURM in it's current form does not support events and notifications. So in order for me to implement what you suggested, i.e., use events to spread information about task migration I would have to implement a new (and sophisticated) SLURM mpi plugin, or force the users to stay with OpenMPI + orted.

There are people working to extend the existing plugin for such purposes. @hppritcha - perhaps you can provide an update? Might be possible for folks to collaborate/contribute to it?

> 
> Regarding that, could you briefly tell me what kind of algorithm is currently implemented in orted? Are all servers notified about the events (collective), or only those, which have clients, who registered for those events?

It is actually more efficient to broadcast the events and let the individual servers determine if they are relevant or not to their local clients. Remember, there is a race condition here between dissemination of events and client registration for them. We actually cache all events on the server in case the client later registers for them (there is an adjustable limit on the number of cached events and/or the length of time they are held in the cache).

> I also have a technical question regarding triggering of the data exchange. I see that committed data is collected in a call to PMIx_Fence(), which takes a list of processes that should participate, and can optionally exchange the data between them. But since a fence is a collective operation, it needs to be executed by all procs in the list at the same time. How do I notify all involved servers about the need to call the collective? It seems that it takes another collective, so I must have missed something?

The fence method of exchanging data is based on the library (MPI or other) standard method of exchanging some level of info during "init". Since all procs have to call "init", there is no need for "triggering" that operation.

For more async exchanges, we use the event mechanism. You might look at the PMIx Group effort (https://pmix.org/pmix-standard/pmix-groups-2/) as an example - that code has been committed to the PMIx master repo.
